#!/usr/bin/env ruby

version   = "#{ARGV.last.match(/\d+/) || 3}".to_i
dummy_app = File.expand_path("../rails-#{version}/dummy", __FILE__)
command   = case ARGV.first
            when "server" , "s"
              {2 => "script/server" , 3 => "rails s"}[version]
            when "console", "c"
              {2 => "script/console", 3 => "rails c"}[version]
            else
              exit
            end

system "rake restore:rails-#{version} && cd #{dummy_app} && #{command}"