require "rich/support"
require "rich/support/core"
require "rich/support/actionpack"
require "rich/support/activesupport"
require "rich/support/rails"
require "rich/support/test"
require "rich/support/version"